services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  admin:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"